#IFDEF SPANISH
      #define STR0001  "¨&Qu‚ es esto?"
      #define STR0002  "Consulta Est ndar"
      #define STR0003  "F3 Disponible..."
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "&What is This?"
	   #define STR0002  "Standard Query"
      #define STR0003  "F3 Available..."
	#ELSE
	   #define STR0001  "&O que ‚ isto?"
	   #define STR0002  "Consulta PadrÆo"
      #define STR0003  "F3 Dispon¡vel..."
	#ENDIF
#ENDIF
