#IFDEF SPANISH
   #define STR0001  "F3 Disponible..."
   #define STR0002  "¨&Qu‚ es esto?"
   #define STR0003  "Consulta Est ndar"
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "F3 Available..."
	   #define STR0002  "&What is This"
	   #define STR0003  "Standard Query"
	#ELSE
	   #define STR0001  "F3 Dispon¡vel..."
	   #define STR0002  "&O que ‚ isto?"
	   #define STR0003  "Consulta PadrÆo"
	#ENDIF
#ENDIF
