#IFDEF SPANISH
   #define STR0001  "Primero Registro"
   #define STR0002  "Retrocede P gina"
   #define STR0003  "Retrocede Registro"
   #define STR0004  "Avanza Registro"
   #define STR0005  "Avanza P gina"
   #define STR0006  "éltimo Registro"
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "First Record"
	   #define STR0002  "Back Page"
	   #define STR0003  "Back Record"
	   #define STR0004  "Foward Record"
	   #define STR0005  "Foward Page"
	   #define STR0006  "Last Record"
	#ELSE
	   #define STR0001  "Primeiro Registro"
	   #define STR0002  "Retrocede P gina"
	   #define STR0003  "Retrocede Registro"
	   #define STR0004  "Avan‡a Registro"
	   #define STR0005  "Avan‡a P gina"
	   #define STR0006  "Último Registro"
	#ENDIF
#ENDIF
